# Usar JDK 21 (el JDK 26 del sistema no es compatible con AGP)
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk

org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
